language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

addons:
  hosts:
    - phabricator.test
  apt:
    packages:
    - nginx

services:
  - mysql

sudo: false

install: travis_retry composer install --prefer-source

before_script: build/before_script.sh

script:
  - composer ci
  - ./vendor/bin/behat

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-de-tech"
    on_success: never
    on_failure: change
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
